---
title: "Lab 1: Getting to Know Each Other"
author: "MATTHEW WYNNE"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Instructions:

The purpose of this lab assignment is to get to know a student in the class, communicate the information learned in writing, and check to see if R Markdown is properly knitting to HTML. Start by putting your full name in the space provided above in the R Markdown file (Replace FIRSTNAME and LASTNAME).

In this first lab, you will interview another student in the class and record this information in the appropriate space below. Your instructor will split you up into groups of 2 (or 3 if necessary). Record the information learned about the individual in the space below after the colon. If you are in a group of 3, make sure you work in a circle where person 1 interviews person 2, person 2 interviews person 3, and person 3 interviews person 1. Don't just get the answers required, but actually talk about them. Ask them questions about their answers and get to know them.

After you are done, knit the R Markdown file to HTML and submit it to Sakai under Lab 1.

# Interview:

- Name of Student: Jerry Xiao

- Origin: Shanghai, China

- Year in School: Junior

- Major or Minor: Double major in Computer Science and Statistics

- Involvement on Campus: He goes to class

- Plans After Graduation: Grad School but not sure what he wants to study

- Biggest Influence in Your Life: Going to the United States to study

- Favorite Thing to Do in Your Free Time: Play with his dog, Lilly

- Positive Thing During the Pandemic: More time to stay at home

- Negative Thing During the Pandemic: Can't see friends as often

